# Global config
project_name: test
cuda: False
gpu_ids: 0
tensorboard: True

# DataLoader config
root_dir: D:/data/img
inference_dir:
val_size: 0.2
label_map_path: ./dataloader/dataset/labelmap/cassava.name
num_workers: 8
pin_memory: True
batch_size: 32
resize: [224, 224] # [H, W]
start_epoch: 0
epoch: 5

# Model config
model: resnet-18
# [ inception-v3, vgg-19, resnet-18, resnet-50, resnet-101, resnet-152, resnext-50, resnext-101, efficientnet-b0 ~ b7]
# optimize learning rate
lr: 0.0001
# opt scheduler
gamma: 0.9
milestones: [10, 20]
model_path: ./run/test/model_best.pth.tar #
resume:  # Path checkpoint


