# Global config
project_name: 'cifar10'
cuda: False
gpu_ids: '0'
tensorboard: True

# DataLoader config
root_dir: '/home/jsk/data/cifar10/'
label_map_path: './dataloader/dataset/labelmap/cifar10.name'
num_workers: 10
pin_memory: True
batch_size: 128
resize: [32, 32]
start_epoch: 0
epoch: 5

# Model config
model: 'resnet-50'
# [ inception-v3, vgg-16, resnet-18, resnet-50, resnet-101, resnet-152, darknet19, efficientnet-b0,
# efficientnet-b1, efficientnet-b2, efficientnet-b3, efficientnet-b4, efficientnet-b5 ]
lr: 0.001
gamma: 0.9
resume: False # Path checkpoint

